### ISSUE TITLE
Grid works incorrectly without `<React.StrictMode>`

### ISSUE THREAD

**Issue by romanstetsyk** [vingeraycn/ruuri#14]
Version: `ruuri v2.0.0`
The grid works incorrectly in production or dev mode without `<React.StrictMode>`.
The following error is printed to the console. 

<img width="653" alt="image" src="https://github.com/vingeraycn/ruuri/assets/25715951/469a2812-9dbe-4355-9f5b-3c4c70b671e1">

[Codesandbox](https://codesandbox.io/p/sandbox/festive-lederberg-5lkmzh?file=%2Fsrc%2Fmain.tsx%3A7%2C23) to reproduce the issue. You can add/remove strict mode to see the error in the console.
Do you think there's a workaround for this?

Thank you for your hard work!

**Comment by vingeraycn** [comment]
Thanks for your feedback!
Unfortunately I am getting busy recently, I can check this issue later. Would you like try to troubleshooting if interested? PR is grateful~
