### ISSUE TITLE
Problem with percentage width on grid items

### ISSUE THREAD

**Issue by blaiseludvig** [vingeraycn/ruuri#21]
Hi @vingeraycn!

First of all, thank you for creating this amazing library. I really wanted to use Muuri in one of my React projects, and it wouldn't have been possible without the help of your library.

The problem I am facing is that I want to set a percentage width on my grid items to create a 3 column layout. If I set a percentage width on the `renderItem`, it behaves unexpectedly and breaks my layout.
I figured out that if I set the percentage width on the `.ruuri-draggable-item` elements, it works perfectly.
The issue seems to be that you're supposed to define the dimensions of your items on the item's container element, instead of the content element.

This is how it's done in the [official example in the Muuri docs](https://github.com/haltu/muuri#getting-started-4). The `width: 100px` is set on the `.item`, and the `.item-content` only has `width: 100%` on it.

I made a [codeSandbox](https://codesandbox.io/s/drag-between-grids-v2-forked-4f4j6g?file=/src/App.js) where I reproduced this bug.
Notice how the first grid's items have their `width` set to `33%`, and the second grid's items don't have their width set at all.

I would be interested in making a PR myself, but I'm not sure about what approach to take. The solution I came up with is exposing the `.ruuri-draggable-item` element in the API, but there could be a different, more elegant approach.

Thanks, your help is greatly appreciated!

**Comment by vingeraycn** [comment]
Hi @blaiseludvig!
Thanks for your like this library at first of all.

We have thought about problems like this before. I think muuri does not force the style to encapsulate into a new class and expose it to the outside in this case, but chooses the way to let the user define the style by himself. Perhaps he wants to give the user a full and flexible usage. ruuri hopes to design concept that is consistent with muuri, which will avoid many problems with the development of muuri in the future.

However, for this question, maybe you can consider trying this method: set the style of the container through the CSS class selector `.ruuri-draggable-item` on the parent node.

Hope it helps you!

**Comment by blaiseludvig** [comment]
Thanks for your response!

I might have been unclear in the suggestion in my previous message. Sorry about that!

Your method would unfortunately not work in my case because I'm using multiple `DraggableGrid`s, and I need to be able to set the widths of the items individually for each grid, but the `.ruuri-draggable-item` class targets every `DraggableGrid`.

I came up with two solutions to this problem.

1. The `.ruuri-draggable-item` element could be optionally passed in through the props, just like the `renderItem`. The downside to this approach is that it complicates the library code a bit.

2. Give `DraggableGrid` an optional prop of type `React.ComponentPropsWithoutRef<"div">` that gets merged into the props of the `.ruuri-draggable-item` elements. This approach produces a flexible API, and it's easy to implement.

I'm interested in making a PR if you like one of these solutions!

**Comment by vingeraycn** [comment]
Thanks for your recommendation!

It's time to expand api for more flexible, I prefers the idea that add props getter function.

There are two APIs designed.
New API design prototype below:
```tsx
// New API for getItemProps
type GetItemProps<T> = (itemData: T, index: number) => Partial<HTMLAttributes<HTMLDivElement>>

// New API for getItemContentProps
type GetItemContentProps<T> = (itemData: T, index: number) => Partial<HTMLAttributes<HTMLDivElement>>

// in interface DraggableGridProps
interface DraggableGridProps<T> {
...
data: T[]
...
+ getItemProps?: GetItemProps<T>
+ getItemContentProps?: GetItemContentProps<T>
...
}


```

How about this solution? @blaiseludvig

**Comment by blaiseludvig** [comment]
Looks good to me! Glad I was able to help.

**Comment by vingeraycn** [comment]
hah! Thanks for your work, PR is welcome :)
