### ISSUE TITLE
The element did not rerender

### ISSUE THREAD

**Issue by duy0ne** [vingeraycn/ruuri#31]
Hi @vingeraycn 

I found another issue
When i update 'data' for DraggableGid component using hook
{ id: 'id-1', name: 'id1' }, { id: 'id-2', name: 'id2' } -> { id: 'id-2', name: 'id2' }, { id: 'id-1', name: 'id1' }

-> The element did not rerender

I expected the result after updating data like picture bellow
![image](https://github.com/vingeraycn/ruuri/assets/27433775/0d1d7235-de03-4618-b1a3-925a883be703)

My code:
![image](https://github.com/vingeraycn/ruuri/assets/27433775/62b7b4d5-88f2-4f62-8eba-1d7bbdd51354)

**Comment by vingeraycn** [comment]
Thanks for your reply!

I reproduced this issue at [codesandbox](https://codesandbox.io/p/sandbox/update-data-property-zs2r4t), and I need to dig out the reason sometime. If you find any threads, PR is also welcome~
