### ISSUE TITLE
Problem starting

### ISSUE THREAD

**Issue by dbx834** [vingeraycn/ruuri#5]
Hello @vingeraycn,

Thanks for your work with this wrapper.

I was trying to get it to work but I see this issue: `Uncaught TypeError: n is undefined.`

This is the stack-trace:
```js
Uncaught TypeError: n is undefined
    q index.es.js:56
    DraggableGrid index.es.js:1571
    Preact 98
    debounceRendering debounceRendering.js:13
    debounceRendering debounceRendering.js:11
    Preact 3
    React 2
    Preact 6
    reactRender app.js:49
    runRender app.js:242
    <anonymous> app.js:253
    setTimeout handler* app.js:252
    promise callback* app.js:197
    promise callback* app.js:74
    js commons.js:2334
    factory commons.js:6767
    __webpack_require__ commons.js:6101
    __webpack_exports__ commons.js:7470
    O commons.js:6150
    <anonymous> commons.js:7471
```

Looking at `dist/index.es.js:56` I see this code: `n = f.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner.`

These are my version:
```json
"muuri": "^0.9.5",
"react": "18.2.0",
"react-dom": "18.2.0",
"ruuri": "^0.1.7",
```

And, this is how I create the component:
```jsx
// ----------------------------------------------------------------------------
// -------------------------------------------------------------------- Imports
// ----------------------------------------------------------------------------
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Libraries
import React, { useRef } from 'react'
import classnames from 'classnames'
import map from 'lodash/map'

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Components
import DraggableGrid, { DraggableItem } from 'ruuri'

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Locals
import smallKey from '../../methods/small-key'

// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Abstractions
// const { Fragment } = React

// ----------------------------------------------------------------------------
// ------------------------------------------------------------------ Component
// ----------------------------------------------------------------------------
/** Grid */
const Grid = ({
  nodes,
  Renderer = (node) => <h2>Need to define a renderer for {node.title}</h2>,
  className,
  itemClassName,
}) => (
  <DraggableGrid
    containerClass={classnames('grid muuri-grid ext-image-fix', className)}
    itemClass={classnames('grid-item muuri-grid-item', itemClassName)}
    dragEnabled={false}
    dragSort={false}
  >
    {map(nodes, (node) => (
      <DraggableItem>
        <Renderer node={node} />
      </DraggableItem>
    ))}
  </DraggableGrid>
)

// ----------------------------------------------------------------------------
// -------------------------------------------------------------------- Exports
// ----------------------------------------------------------------------------
export default Grid
```

Could you please comment?

Thanks!

**Comment by vingeraycn** [comment]
Hi @dbx834 
Thanks for the detailed info, I'll take a look at the question later today

**Comment by vingeraycn** [comment]
Hi @dbx834 
I pasted your code on [Codesandbox](https://codesandbox.io/s/cocky-cohen-zypcxx?file=/src/Grid.tsx) but it doesn't reproduce your problem, am I missing some key information? If possible, can this issue be reproduced on Codesandbox? Thank u

**Comment by dbx834** [comment]
Thanks for checking it out. Your sandbox certainly is working. Yes I did miss some information. I didn't include the fact that I'm using `preact` ([ref](https://preactjs.com/)) and `preact-compat`([ref](https://preactjs.com/guide/v10/switching-to-preact/)). I'll go more into it and write again soon, and this time with a sandbox.

**Comment by dbx834** [comment]
So, I was able to sort it out.

I use [this gatsby plugin] (https://www.gatsbyjs.com/plugins/gatsby-plugin-preact/), which replaces or updates references to [these react libraries](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-preact/src/gatsby-node.js#L65-L68) at runtime.

The issue, as I guessed, was because of this. Precisely – because at runtime a reference couldn't be found in the code.

How I solved it was that I copied the files in your source folder and used them as the component instead of the packaged files. Then, I just added a reference to React in `DraggableGrid.tsx` and `DraggableItem.tsx`, and it works.

This is a weird, rare issue. Noting it for someone else who maybe up against it.

Thanks, once again, @vingeraycn!

**Comment by vingeraycn** [comment]
> So, I was able to sort it out.
> 
> I use [this gatsby plugin](https://www.gatsbyjs.com/plugins/gatsby-plugin-preact/), which replaces or updates references to [these react libraries](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-preact/src/gatsby-node.js#L65-L68) with the appropriate `preact` libraries at runtime.
> 
> The issue, as I guessed, was because of this. Precisely – because at runtime a reference couldn't be found in the code. How I solved it was that I copied the files in your source folder and used them as the component instead of the packaged files. Then, I just added a reference to React in `DraggableGrid.tsx` and `DraggableItem.tsx`, and it works.
> 
> This is a weird, rare issue. Noting it for someone else who maybe up against it.
> 
> Thanks, once again, @vingeraycn!

I'm glad to see the progress of the problem. I think this may have something to do with the concept of `ruuri`. `ruuri` relies on React's runtime, but does not mix React when packaging, but chooses to rely on the React version of the user's current project. It was true that Preact was not considered at first, but thank you for exposing it. @dbx834
